### ISSUE TITLE
Follow Julia package standards

### ISSUE THREAD

**Issue by Ismael-VC** [jkroso/Emitter.jl#1]
- Capitalize pkg name, `Emitter` instead of `emitter`.
- You can run `Pkg.generate("Emitter", "MIT")` in order to create an skeleton repo for your package, with `travis.yml` included for CI
- code goes in `src` dir, tests in `test`, etc.

This would allow other users to simply run `Pkg.clone("https://github.com/jkroso/Emitter.jl")` in order to install and run the tests, even if it's not registered as an official package in `METADATA`.

**Comment by jkroso** [comment]
I'm just experimenting with Julia and its package system is the one part of it I think is objectively bad so I'm not very excited by this proposal. That said none of the things I would need to do are that bad so if you PR it i'll merge

**Comment by Ismael-VC** [comment]
What do you dislike about it? Could you give me an example of a pkg manager you think is great?

Please consider raising issues, if you note those things haven't been reported yet, so we can get a chance to fix them.

A PR would be even better! 

I'll be sending you my PR shortly. ;)

**Comment by Ismael-VC** [comment]
@jkroso do you have a license in mind?

**Comment by Ismael-VC** [comment]
``` julia
help?> Pkg.generate
INFO: Loading help data...
Base.Pkg.generate(pkg, license)

   Generate a new package named "pkg" with one of these license
   keys: ""MIT"" or ""BSD"". If you want to make a package
   with a different license, you can edit it afterwards. Generate
   creates a git repo at "Pkg.dir(pkg)" for the package and inside
   it "LICENSE.md", "README.md", the julia entrypoint
   "$pkg/src/$pkg.jl", and a travis test file, ".travis.yml".

julia> Pkg.generate("Emitter", "MIT")
INFO: Initializing Emitter repo: /Users/MexLavuDev/.julia/v0.3/Emitter
INFO: Generating LICENSE.md
INFO: Generating README.md
INFO: Generating src/Emitter.jl
INFO: Generating test/runtests.jl
INFO: Generating .travis.yml
INFO: Generating .gitignore
INFO: Committing Emitter generated files
```

**Comment by jkroso** [comment]
> What do you dislike about it?

It doesn't handle versions robustly at all. That's the only part I can say is Objectively bad. And the package format is ugly to my eyes.

> Could you give me an example of a pkg manager you think is great?

None exist yet but if [this idea](https://github.com/jbenet/random-ideas/issues/27) was built it would be. [jkroso/Kip.jl](https://github.com/jkroso/Kip.jl) is okay; it handles versions and allows pretty packages.

I've spoken about it in JuliaLang/julia#8015 but I don't think I would be able to convince everyone to deprecate their existing packages until we have a great solution

**Comment by jkroso** [comment]
> do you have a license in mind?

MIT

**Comment by Ismael-VC** [comment]
Which version are you using? where does `@require` come from?

> I've spoken about it in JuliaLang/julia#8015 

That's great!

**Comment by Ismael-VC** [comment]
> It doesn't handle versions robustly at all.

That´s fixable IMHO

> the package format is ugly to my eyes.

Why do you think it´s ugly?

**Comment by jkroso** [comment]
'@require' comes from requirer.jl. I need to merge that project into kip.jl

**Comment by jkroso** [comment]
> Why do you think it´s ugly?
- module wrappers to define a module. These cause people to use include inside their modules and that makes to hard to understand projects
- metadata: no need really and it's a pain to maintain
- enforced module structure: sucks for simple modules and the runtests.jl thing never suits me

**Comment by Ismael-VC** [comment]
@jkroso I understand now, thank you very much for taking your time explaining this to me. Your [greed](http://julialang.org/blog/2012/02/why-we-created-julia) is very welcome ...keep it coming! :sparkles:
